# Temas (Importação)
# ------------------------------------------------------------------------------
# include themes/latte.conf
# include themes/frappe.conf
# include themes/macchiato.conf
include themes/mocha.conf
# include themes/tokyo_night.conf
# include themes/tokyo_night_storm.conf



# Janela e Aparência (window)
hide_window_decorations yes
background_opacity       0.85
window_padding_width     10


# Fontes (font)
font_size                12.0

font_family              JetBrainsMono Nerd Font
bold_font                JetBrainsMono Nerd Font Bold
italic_font              JetBrainsMono Nerd Font Italic
bold_italic_font         JetBrainsMono Nerd Font Bold Italic


# Cursor
shell_integration        no-cursor
cursor_shape             block
cursor_blink_interval    0.5


# Seleção e Área de Transferência
copy_on_select          yes
enable_audio_bell       no
